### ISSUE TITLE
Training with Visual Genome

### ISSUE THREAD

**Issue by pqviet** [linjieli222/VQA_ReGAT#18] opened 2020-06-26 08:21 UTC
When trying to train with the train/val splits and Visual Genome
python main.py --config config/butd_vqa.json --seed 1 --use_both --use_vg

I got this error
nParams=        41192896
optim: adamax lr=0.0010, decay_step=2, decay_rate=0.25,grad_clip=0.25
LR decay epochs: 15,17,19
gradual warmup lr: 0.0005
Traceback (most recent call last):
  File "main.py", line 289, in <module>
    train(model, train_loader, eval_loader, args, device)
  File "train.py", line 91, in train
    sem_adj_matrix) in enumerate(train_loader):
  File "python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "utils.py", line 172, in trim_collate
    return [trim_collate(samples) for samples in transposed]
  File "utils.py", line 172, in <listcomp>
    return [trim_collate(samples) for samples in transposed]
  File "utils.py", line 161, in trim_collate
    return torch.LongTensor(batch)
TypeError: an integer is required (got type str)

I think the problem is in the process of encoding Genome questions. Do you have any ideas?

**Comment by linjieli222** [comment] 2020-08-13 10:41
Sorry for the late reply. Are you still facing the same issue? I don't see similar error when training with Visual Genome.

**Comment by pqviet** [comment] 2020-08-18 08:21
The problem remains unsolved for me

**Comment by linjieli222** [comment] 2020-08-18 17:38
I suspect is the question id. But to further debug, you can set the num_workers in data loader to 0 and use ipdb. Let me know if it helps.

**Comment by Zou-123** [comment] 2020-09-17 10:02
> I suspect is the question id. But to further debug, you can set the num_workers in data loader to 0 and use ipdb. Let me know if it helps.

I have the same problem in use VG, in your code, the return values of VGFeatureDataset is that return features, normalized_bb, question, target, raw_question,\
            image_id, bb, spatial_adj_matrix, semantic_adj_matrix,

I think the problem is from return value(raw_question)

in the VQAFeatureDataset, the return values is that return features, normalized_bb, question, target,\
                  question_id, image_id, bb, spatial_adj_matrix,\
                semantic_adj_matrix

so I use (question_id) instead of (raw_question) in the return values of VGFeatureDataset, but there get the error:
/pytorch/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [20,0,0], thread: [39,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    train(model, train_loader, eval_loader, args, device)
  File "/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/VQA_reGAT/train.py", line 113, in train
    spa_adj_matrix, target)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/VQA_reGAT/model/regat.py", line 51, in forward
    q_emb_seq = self.q_emb.forward_all(w_emb)  # [batch, q_len, q_dim]
  File "/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/media/xatu/83fce006-3950-4630-8a4d-d5db0016f6cf2/zpr/VQA_reGAT/model/language_model.py", line 111, in forward_all
    output, hidden = self.rnn(x, hidden)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xatu/anaconda2/envs/zpr/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA error: device-side assert triggered

can you give me some suggestions for thr error? looking forward your reply, think you very much!

**Comment by linjieli222** [comment] 2020-09-28 20:51
Closing this due to no further activities.

**Closed as completed by linjieli222** 2020-09-28 20:51 UTC
